server:
  servlet:
    context-path: /warehouse
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/warehouse-service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:db-password}
    driverClassName: org.postgresql.Driver
